apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      # Init container to install SOPS and age
      initContainers:
        - name: install-sops
          image: alpine:3.19
          command:
            - sh
            - -c
            - |
              set -e
              echo "Installing SOPS and age..."

              # Install dependencies
              apk add --no-cache curl

              # Install SOPS
              SOPS_VERSION="3.11.0"
              curl -Lo /custom-tools/sops \
                https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64
              chmod +x /custom-tools/sops

              # Install age
              AGE_VERSION="1.2.1"
              curl -Lo age.tar.gz \
                https://github.com/FiloSottile/age/releases/download/v${AGE_VERSION}/age-v${AGE_VERSION}-linux-amd64.tar.gz
              tar -xzf age.tar.gz -C /tmp
              mv /tmp/age/age /custom-tools/age
              mv /tmp/age/age-keygen /custom-tools/age-keygen
              chmod +x /custom-tools/age /custom-tools/age-keygen

              # Install kustomize
              KUSTOMIZE_VERSION="5.5.0"
              curl -Lo kustomize.tar.gz \
                https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
              tar -xzf kustomize.tar.gz -C /custom-tools
              chmod +x /custom-tools/kustomize

              echo "Installation complete!"
              ls -la /custom-tools/
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools

      containers:
        - name: argocd-repo-server
          # Add SOPS environment variables
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /sops-age/keys.txt
            - name: XDG_CONFIG_HOME
              value: /.config
          # Mount volumes for SOPS key and custom tools
          volumeMounts:
            - name: sops-age
              mountPath: /sops-age
              readOnly: true
            - name: custom-tools
              mountPath: /usr/local/bin/sops
              subPath: sops
            - name: custom-tools
              mountPath: /usr/local/bin/age
              subPath: age
            - name: custom-tools
              mountPath: /usr/local/bin/age-keygen
              subPath: age-keygen
            - name: custom-tools
              mountPath: /usr/local/bin/kustomize
              subPath: kustomize

      volumes:
        - name: sops-age
          secret:
            secretName: sops-age
        - name: custom-tools
          emptyDir: {}
