# SOPS configuration for secret encryption
# Uses age encryption (https://github.com/FiloSottile/age)

creation_rules:
  # Development environment
  - path_regex: secrets/dev/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      # TODO: Add age public key for dev environment
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # Staging environment
  - path_regex: secrets/staging/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      # TODO: Add age public key for staging environment
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # Production environment
  - path_regex: secrets/prod/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      # TODO: Add age public key for production environment
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# How to encrypt secrets:
#   sops -e secrets/dev/secrets.yaml > secrets/dev/secrets.enc.yaml
#
# How to decrypt secrets:
#   sops -d secrets/dev/secrets.enc.yaml
#
# How to edit encrypted secrets:
#   sops secrets/dev/secrets.enc.yaml
